GET  http://localhost:5000/teams

###
POST http://localhost:5000/teams
Content-type:application/json

{
    "name":"Dallas mavericks",
    "conference":"West"
}

###
DELETE http://localhost:5000/teams/64a2b3f8fcf322224ace0744



###
PUT http://localhost:5000/teams/64a2bdd390d8365252357eac
Content-Type: application/json

{
    "conference":"West"
}

###
GET  http://localhost:5000/players

###
GET  http://localhost:5000/players/64a2dbea72e1c1d6aeebc75a

###
POST http://localhost:5000/players
Content-Type: application/json

{
    "name":"Luka Doncic",
    "team":"64a2cc89730ab4cc4a7b68ea",
    "height":2.01
}

###
DELETE http://localhost:5000/players/64a2dbe272e1c1d6aeebc758
###
PUT http://localhost:5000/players/64a2dbea72e1c1d6aeebc75a
Content-Type: application/json

{
    "name": "HalleLLuka Doncicuka"
}
